# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/arotem/Dev/numeric-lib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/arotem/Dev/numeric-lib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arotem/Dev/numeric-lib/CMakeFiles /home/arotem/Dev/numeric-lib/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arotem/Dev/numeric-lib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named numerics

# Build rule for target.
numerics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 numerics
.PHONY : numerics

# fast build rule for target.
numerics/fast:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/build
.PHONY : numerics/fast

src/ODEs/IVP_solve.o: src/ODEs/IVP_solve.cpp.o

.PHONY : src/ODEs/IVP_solve.o

# target to build an object file
src/ODEs/IVP_solve.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/IVP_solve.cpp.o
.PHONY : src/ODEs/IVP_solve.cpp.o

src/ODEs/IVP_solve.i: src/ODEs/IVP_solve.cpp.i

.PHONY : src/ODEs/IVP_solve.i

# target to preprocess a source file
src/ODEs/IVP_solve.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/IVP_solve.cpp.i
.PHONY : src/ODEs/IVP_solve.cpp.i

src/ODEs/IVP_solve.s: src/ODEs/IVP_solve.cpp.s

.PHONY : src/ODEs/IVP_solve.s

# target to generate assembly for a file
src/ODEs/IVP_solve.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/IVP_solve.cpp.s
.PHONY : src/ODEs/IVP_solve.cpp.s

src/ODEs/am1.o: src/ODEs/am1.cpp.o

.PHONY : src/ODEs/am1.o

# target to build an object file
src/ODEs/am1.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/am1.cpp.o
.PHONY : src/ODEs/am1.cpp.o

src/ODEs/am1.i: src/ODEs/am1.cpp.i

.PHONY : src/ODEs/am1.i

# target to preprocess a source file
src/ODEs/am1.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/am1.cpp.i
.PHONY : src/ODEs/am1.cpp.i

src/ODEs/am1.s: src/ODEs/am1.cpp.s

.PHONY : src/ODEs/am1.s

# target to generate assembly for a file
src/ODEs/am1.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/am1.cpp.s
.PHONY : src/ODEs/am1.cpp.s

src/ODEs/am2.o: src/ODEs/am2.cpp.o

.PHONY : src/ODEs/am2.o

# target to build an object file
src/ODEs/am2.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/am2.cpp.o
.PHONY : src/ODEs/am2.cpp.o

src/ODEs/am2.i: src/ODEs/am2.cpp.i

.PHONY : src/ODEs/am2.i

# target to preprocess a source file
src/ODEs/am2.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/am2.cpp.i
.PHONY : src/ODEs/am2.cpp.i

src/ODEs/am2.s: src/ODEs/am2.cpp.s

.PHONY : src/ODEs/am2.s

# target to generate assembly for a file
src/ODEs/am2.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/am2.cpp.s
.PHONY : src/ODEs/am2.cpp.s

src/ODEs/bdf23.o: src/ODEs/bdf23.cpp.o

.PHONY : src/ODEs/bdf23.o

# target to build an object file
src/ODEs/bdf23.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/bdf23.cpp.o
.PHONY : src/ODEs/bdf23.cpp.o

src/ODEs/bdf23.i: src/ODEs/bdf23.cpp.i

.PHONY : src/ODEs/bdf23.i

# target to preprocess a source file
src/ODEs/bdf23.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/bdf23.cpp.i
.PHONY : src/ODEs/bdf23.cpp.i

src/ODEs/bdf23.s: src/ODEs/bdf23.cpp.s

.PHONY : src/ODEs/bdf23.s

# target to generate assembly for a file
src/ODEs/bdf23.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/bdf23.cpp.s
.PHONY : src/ODEs/bdf23.cpp.s

src/ODEs/cheb.o: src/ODEs/cheb.cpp.o

.PHONY : src/ODEs/cheb.o

# target to build an object file
src/ODEs/cheb.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/cheb.cpp.o
.PHONY : src/ODEs/cheb.cpp.o

src/ODEs/cheb.i: src/ODEs/cheb.cpp.i

.PHONY : src/ODEs/cheb.i

# target to preprocess a source file
src/ODEs/cheb.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/cheb.cpp.i
.PHONY : src/ODEs/cheb.cpp.i

src/ODEs/cheb.s: src/ODEs/cheb.cpp.s

.PHONY : src/ODEs/cheb.s

# target to generate assembly for a file
src/ODEs/cheb.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/cheb.cpp.s
.PHONY : src/ODEs/cheb.cpp.s

src/ODEs/diffmat.o: src/ODEs/diffmat.cpp.o

.PHONY : src/ODEs/diffmat.o

# target to build an object file
src/ODEs/diffmat.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/diffmat.cpp.o
.PHONY : src/ODEs/diffmat.cpp.o

src/ODEs/diffmat.i: src/ODEs/diffmat.cpp.i

.PHONY : src/ODEs/diffmat.i

# target to preprocess a source file
src/ODEs/diffmat.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/diffmat.cpp.i
.PHONY : src/ODEs/diffmat.cpp.i

src/ODEs/diffmat.s: src/ODEs/diffmat.cpp.s

.PHONY : src/ODEs/diffmat.s

# target to generate assembly for a file
src/ODEs/diffmat.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/diffmat.cpp.s
.PHONY : src/ODEs/diffmat.cpp.s

src/ODEs/ivp_events.o: src/ODEs/ivp_events.cpp.o

.PHONY : src/ODEs/ivp_events.o

# target to build an object file
src/ODEs/ivp_events.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/ivp_events.cpp.o
.PHONY : src/ODEs/ivp_events.cpp.o

src/ODEs/ivp_events.i: src/ODEs/ivp_events.cpp.i

.PHONY : src/ODEs/ivp_events.i

# target to preprocess a source file
src/ODEs/ivp_events.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/ivp_events.cpp.i
.PHONY : src/ODEs/ivp_events.cpp.i

src/ODEs/ivp_events.s: src/ODEs/ivp_events.cpp.s

.PHONY : src/ODEs/ivp_events.s

# target to generate assembly for a file
src/ODEs/ivp_events.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/ivp_events.cpp.s
.PHONY : src/ODEs/ivp_events.cpp.s

src/ODEs/linear_bvp.o: src/ODEs/linear_bvp.cpp.o

.PHONY : src/ODEs/linear_bvp.o

# target to build an object file
src/ODEs/linear_bvp.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/linear_bvp.cpp.o
.PHONY : src/ODEs/linear_bvp.cpp.o

src/ODEs/linear_bvp.i: src/ODEs/linear_bvp.cpp.i

.PHONY : src/ODEs/linear_bvp.i

# target to preprocess a source file
src/ODEs/linear_bvp.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/linear_bvp.cpp.i
.PHONY : src/ODEs/linear_bvp.cpp.i

src/ODEs/linear_bvp.s: src/ODEs/linear_bvp.cpp.s

.PHONY : src/ODEs/linear_bvp.s

# target to generate assembly for a file
src/ODEs/linear_bvp.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/linear_bvp.cpp.s
.PHONY : src/ODEs/linear_bvp.cpp.s

src/ODEs/nonlin_bvp.o: src/ODEs/nonlin_bvp.cpp.o

.PHONY : src/ODEs/nonlin_bvp.o

# target to build an object file
src/ODEs/nonlin_bvp.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/nonlin_bvp.cpp.o
.PHONY : src/ODEs/nonlin_bvp.cpp.o

src/ODEs/nonlin_bvp.i: src/ODEs/nonlin_bvp.cpp.i

.PHONY : src/ODEs/nonlin_bvp.i

# target to preprocess a source file
src/ODEs/nonlin_bvp.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/nonlin_bvp.cpp.i
.PHONY : src/ODEs/nonlin_bvp.cpp.i

src/ODEs/nonlin_bvp.s: src/ODEs/nonlin_bvp.cpp.s

.PHONY : src/ODEs/nonlin_bvp.s

# target to generate assembly for a file
src/ODEs/nonlin_bvp.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/nonlin_bvp.cpp.s
.PHONY : src/ODEs/nonlin_bvp.cpp.s

src/ODEs/poisson.o: src/ODEs/poisson.cpp.o

.PHONY : src/ODEs/poisson.o

# target to build an object file
src/ODEs/poisson.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/poisson.cpp.o
.PHONY : src/ODEs/poisson.cpp.o

src/ODEs/poisson.i: src/ODEs/poisson.cpp.i

.PHONY : src/ODEs/poisson.i

# target to preprocess a source file
src/ODEs/poisson.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/poisson.cpp.i
.PHONY : src/ODEs/poisson.cpp.i

src/ODEs/poisson.s: src/ODEs/poisson.cpp.s

.PHONY : src/ODEs/poisson.s

# target to generate assembly for a file
src/ODEs/poisson.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/poisson.cpp.s
.PHONY : src/ODEs/poisson.cpp.s

src/ODEs/rk4.o: src/ODEs/rk4.cpp.o

.PHONY : src/ODEs/rk4.o

# target to build an object file
src/ODEs/rk4.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/rk4.cpp.o
.PHONY : src/ODEs/rk4.cpp.o

src/ODEs/rk4.i: src/ODEs/rk4.cpp.i

.PHONY : src/ODEs/rk4.i

# target to preprocess a source file
src/ODEs/rk4.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/rk4.cpp.i
.PHONY : src/ODEs/rk4.cpp.i

src/ODEs/rk4.s: src/ODEs/rk4.cpp.s

.PHONY : src/ODEs/rk4.s

# target to generate assembly for a file
src/ODEs/rk4.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/rk4.cpp.s
.PHONY : src/ODEs/rk4.cpp.s

src/ODEs/rk45.o: src/ODEs/rk45.cpp.o

.PHONY : src/ODEs/rk45.o

# target to build an object file
src/ODEs/rk45.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/rk45.cpp.o
.PHONY : src/ODEs/rk45.cpp.o

src/ODEs/rk45.i: src/ODEs/rk45.cpp.i

.PHONY : src/ODEs/rk45.i

# target to preprocess a source file
src/ODEs/rk45.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/rk45.cpp.i
.PHONY : src/ODEs/rk45.cpp.i

src/ODEs/rk45.s: src/ODEs/rk45.cpp.s

.PHONY : src/ODEs/rk45.s

# target to generate assembly for a file
src/ODEs/rk45.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/rk45.cpp.s
.PHONY : src/ODEs/rk45.cpp.s

src/ODEs/rk5i.o: src/ODEs/rk5i.cpp.o

.PHONY : src/ODEs/rk5i.o

# target to build an object file
src/ODEs/rk5i.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/rk5i.cpp.o
.PHONY : src/ODEs/rk5i.cpp.o

src/ODEs/rk5i.i: src/ODEs/rk5i.cpp.i

.PHONY : src/ODEs/rk5i.i

# target to preprocess a source file
src/ODEs/rk5i.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/rk5i.cpp.i
.PHONY : src/ODEs/rk5i.cpp.i

src/ODEs/rk5i.s: src/ODEs/rk5i.cpp.s

.PHONY : src/ODEs/rk5i.s

# target to generate assembly for a file
src/ODEs/rk5i.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/ODEs/rk5i.cpp.s
.PHONY : src/ODEs/rk5i.cpp.s

src/finite_dif.o: src/finite_dif.cpp.o

.PHONY : src/finite_dif.o

# target to build an object file
src/finite_dif.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/finite_dif.cpp.o
.PHONY : src/finite_dif.cpp.o

src/finite_dif.i: src/finite_dif.cpp.i

.PHONY : src/finite_dif.i

# target to preprocess a source file
src/finite_dif.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/finite_dif.cpp.i
.PHONY : src/finite_dif.cpp.i

src/finite_dif.s: src/finite_dif.cpp.s

.PHONY : src/finite_dif.s

# target to generate assembly for a file
src/finite_dif.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/finite_dif.cpp.s
.PHONY : src/finite_dif.cpp.s

src/integration/integrate.o: src/integration/integrate.cpp.o

.PHONY : src/integration/integrate.o

# target to build an object file
src/integration/integrate.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/integration/integrate.cpp.o
.PHONY : src/integration/integrate.cpp.o

src/integration/integrate.i: src/integration/integrate.cpp.i

.PHONY : src/integration/integrate.i

# target to preprocess a source file
src/integration/integrate.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/integration/integrate.cpp.i
.PHONY : src/integration/integrate.cpp.i

src/integration/integrate.s: src/integration/integrate.cpp.s

.PHONY : src/integration/integrate.s

# target to generate assembly for a file
src/integration/integrate.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/integration/integrate.cpp.s
.PHONY : src/integration/integrate.cpp.s

src/integration/mcIntegrate.o: src/integration/mcIntegrate.cpp.o

.PHONY : src/integration/mcIntegrate.o

# target to build an object file
src/integration/mcIntegrate.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/integration/mcIntegrate.cpp.o
.PHONY : src/integration/mcIntegrate.cpp.o

src/integration/mcIntegrate.i: src/integration/mcIntegrate.cpp.i

.PHONY : src/integration/mcIntegrate.i

# target to preprocess a source file
src/integration/mcIntegrate.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/integration/mcIntegrate.cpp.i
.PHONY : src/integration/mcIntegrate.cpp.i

src/integration/mcIntegrate.s: src/integration/mcIntegrate.cpp.s

.PHONY : src/integration/mcIntegrate.s

# target to generate assembly for a file
src/integration/mcIntegrate.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/integration/mcIntegrate.cpp.s
.PHONY : src/integration/mcIntegrate.cpp.s

src/interpolation/cinterp.o: src/interpolation/cinterp.cpp.o

.PHONY : src/interpolation/cinterp.o

# target to build an object file
src/interpolation/cinterp.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/interpolation/cinterp.cpp.o
.PHONY : src/interpolation/cinterp.cpp.o

src/interpolation/cinterp.i: src/interpolation/cinterp.cpp.i

.PHONY : src/interpolation/cinterp.i

# target to preprocess a source file
src/interpolation/cinterp.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/interpolation/cinterp.cpp.i
.PHONY : src/interpolation/cinterp.cpp.i

src/interpolation/cinterp.s: src/interpolation/cinterp.cpp.s

.PHONY : src/interpolation/cinterp.s

# target to generate assembly for a file
src/interpolation/cinterp.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/interpolation/cinterp.cpp.s
.PHONY : src/interpolation/cinterp.cpp.s

src/interpolation/interp.o: src/interpolation/interp.cpp.o

.PHONY : src/interpolation/interp.o

# target to build an object file
src/interpolation/interp.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/interpolation/interp.cpp.o
.PHONY : src/interpolation/interp.cpp.o

src/interpolation/interp.i: src/interpolation/interp.cpp.i

.PHONY : src/interpolation/interp.i

# target to preprocess a source file
src/interpolation/interp.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/interpolation/interp.cpp.i
.PHONY : src/interpolation/interp.cpp.i

src/interpolation/interp.s: src/interpolation/interp.cpp.s

.PHONY : src/interpolation/interp.s

# target to generate assembly for a file
src/interpolation/interp.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/interpolation/interp.cpp.s
.PHONY : src/interpolation/interp.cpp.s

src/interpolation/polyInterp.o: src/interpolation/polyInterp.cpp.o

.PHONY : src/interpolation/polyInterp.o

# target to build an object file
src/interpolation/polyInterp.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/interpolation/polyInterp.cpp.o
.PHONY : src/interpolation/polyInterp.cpp.o

src/interpolation/polyInterp.i: src/interpolation/polyInterp.cpp.i

.PHONY : src/interpolation/polyInterp.i

# target to preprocess a source file
src/interpolation/polyInterp.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/interpolation/polyInterp.cpp.i
.PHONY : src/interpolation/polyInterp.cpp.i

src/interpolation/polyInterp.s: src/interpolation/polyInterp.cpp.s

.PHONY : src/interpolation/polyInterp.s

# target to generate assembly for a file
src/interpolation/polyInterp.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/interpolation/polyInterp.cpp.s
.PHONY : src/interpolation/polyInterp.cpp.s

src/interpolation/sincInterp.o: src/interpolation/sincInterp.cpp.o

.PHONY : src/interpolation/sincInterp.o

# target to build an object file
src/interpolation/sincInterp.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/interpolation/sincInterp.cpp.o
.PHONY : src/interpolation/sincInterp.cpp.o

src/interpolation/sincInterp.i: src/interpolation/sincInterp.cpp.i

.PHONY : src/interpolation/sincInterp.i

# target to preprocess a source file
src/interpolation/sincInterp.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/interpolation/sincInterp.cpp.i
.PHONY : src/interpolation/sincInterp.cpp.i

src/interpolation/sincInterp.s: src/interpolation/sincInterp.cpp.s

.PHONY : src/interpolation/sincInterp.s

# target to generate assembly for a file
src/interpolation/sincInterp.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/interpolation/sincInterp.cpp.s
.PHONY : src/interpolation/sincInterp.cpp.s

src/kmeans.o: src/kmeans.cpp.o

.PHONY : src/kmeans.o

# target to build an object file
src/kmeans.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/kmeans.cpp.o
.PHONY : src/kmeans.cpp.o

src/kmeans.i: src/kmeans.cpp.i

.PHONY : src/kmeans.i

# target to preprocess a source file
src/kmeans.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/kmeans.cpp.i
.PHONY : src/kmeans.cpp.i

src/kmeans.s: src/kmeans.cpp.s

.PHONY : src/kmeans.s

# target to generate assembly for a file
src/kmeans.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/kmeans.cpp.s
.PHONY : src/kmeans.cpp.s

src/nonlinear/adj_gd.o: src/nonlinear/adj_gd.cpp.o

.PHONY : src/nonlinear/adj_gd.o

# target to build an object file
src/nonlinear/adj_gd.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/adj_gd.cpp.o
.PHONY : src/nonlinear/adj_gd.cpp.o

src/nonlinear/adj_gd.i: src/nonlinear/adj_gd.cpp.i

.PHONY : src/nonlinear/adj_gd.i

# target to preprocess a source file
src/nonlinear/adj_gd.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/adj_gd.cpp.i
.PHONY : src/nonlinear/adj_gd.cpp.i

src/nonlinear/adj_gd.s: src/nonlinear/adj_gd.cpp.s

.PHONY : src/nonlinear/adj_gd.s

# target to generate assembly for a file
src/nonlinear/adj_gd.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/adj_gd.cpp.s
.PHONY : src/nonlinear/adj_gd.cpp.s

src/nonlinear/bfgs.o: src/nonlinear/bfgs.cpp.o

.PHONY : src/nonlinear/bfgs.o

# target to build an object file
src/nonlinear/bfgs.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/bfgs.cpp.o
.PHONY : src/nonlinear/bfgs.cpp.o

src/nonlinear/bfgs.i: src/nonlinear/bfgs.cpp.i

.PHONY : src/nonlinear/bfgs.i

# target to preprocess a source file
src/nonlinear/bfgs.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/bfgs.cpp.i
.PHONY : src/nonlinear/bfgs.cpp.i

src/nonlinear/bfgs.s: src/nonlinear/bfgs.cpp.s

.PHONY : src/nonlinear/bfgs.s

# target to generate assembly for a file
src/nonlinear/bfgs.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/bfgs.cpp.s
.PHONY : src/nonlinear/bfgs.cpp.s

src/nonlinear/broyd.o: src/nonlinear/broyd.cpp.o

.PHONY : src/nonlinear/broyd.o

# target to build an object file
src/nonlinear/broyd.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/broyd.cpp.o
.PHONY : src/nonlinear/broyd.cpp.o

src/nonlinear/broyd.i: src/nonlinear/broyd.cpp.i

.PHONY : src/nonlinear/broyd.i

# target to preprocess a source file
src/nonlinear/broyd.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/broyd.cpp.i
.PHONY : src/nonlinear/broyd.cpp.i

src/nonlinear/broyd.s: src/nonlinear/broyd.cpp.s

.PHONY : src/nonlinear/broyd.s

# target to generate assembly for a file
src/nonlinear/broyd.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/broyd.cpp.s
.PHONY : src/nonlinear/broyd.cpp.s

src/nonlinear/cgd.o: src/nonlinear/cgd.cpp.o

.PHONY : src/nonlinear/cgd.o

# target to build an object file
src/nonlinear/cgd.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/cgd.cpp.o
.PHONY : src/nonlinear/cgd.cpp.o

src/nonlinear/cgd.i: src/nonlinear/cgd.cpp.i

.PHONY : src/nonlinear/cgd.i

# target to preprocess a source file
src/nonlinear/cgd.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/cgd.cpp.i
.PHONY : src/nonlinear/cgd.cpp.i

src/nonlinear/cgd.s: src/nonlinear/cgd.cpp.s

.PHONY : src/nonlinear/cgd.s

# target to generate assembly for a file
src/nonlinear/cgd.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/cgd.cpp.s
.PHONY : src/nonlinear/cgd.cpp.s

src/nonlinear/fpi.o: src/nonlinear/fpi.cpp.o

.PHONY : src/nonlinear/fpi.o

# target to build an object file
src/nonlinear/fpi.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/fpi.cpp.o
.PHONY : src/nonlinear/fpi.cpp.o

src/nonlinear/fpi.i: src/nonlinear/fpi.cpp.i

.PHONY : src/nonlinear/fpi.i

# target to preprocess a source file
src/nonlinear/fpi.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/fpi.cpp.i
.PHONY : src/nonlinear/fpi.cpp.i

src/nonlinear/fpi.s: src/nonlinear/fpi.cpp.s

.PHONY : src/nonlinear/fpi.s

# target to generate assembly for a file
src/nonlinear/fpi.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/fpi.cpp.s
.PHONY : src/nonlinear/fpi.cpp.s

src/nonlinear/fzero.o: src/nonlinear/fzero.cpp.o

.PHONY : src/nonlinear/fzero.o

# target to build an object file
src/nonlinear/fzero.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/fzero.cpp.o
.PHONY : src/nonlinear/fzero.cpp.o

src/nonlinear/fzero.i: src/nonlinear/fzero.cpp.i

.PHONY : src/nonlinear/fzero.i

# target to preprocess a source file
src/nonlinear/fzero.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/fzero.cpp.i
.PHONY : src/nonlinear/fzero.cpp.i

src/nonlinear/fzero.s: src/nonlinear/fzero.cpp.s

.PHONY : src/nonlinear/fzero.s

# target to generate assembly for a file
src/nonlinear/fzero.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/fzero.cpp.s
.PHONY : src/nonlinear/fzero.cpp.s

src/nonlinear/genetic.o: src/nonlinear/genetic.cpp.o

.PHONY : src/nonlinear/genetic.o

# target to build an object file
src/nonlinear/genetic.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/genetic.cpp.o
.PHONY : src/nonlinear/genetic.cpp.o

src/nonlinear/genetic.i: src/nonlinear/genetic.cpp.i

.PHONY : src/nonlinear/genetic.i

# target to preprocess a source file
src/nonlinear/genetic.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/genetic.cpp.i
.PHONY : src/nonlinear/genetic.cpp.i

src/nonlinear/genetic.s: src/nonlinear/genetic.cpp.s

.PHONY : src/nonlinear/genetic.s

# target to generate assembly for a file
src/nonlinear/genetic.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/genetic.cpp.s
.PHONY : src/nonlinear/genetic.cpp.s

src/nonlinear/line_min.o: src/nonlinear/line_min.cpp.o

.PHONY : src/nonlinear/line_min.o

# target to build an object file
src/nonlinear/line_min.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/line_min.cpp.o
.PHONY : src/nonlinear/line_min.cpp.o

src/nonlinear/line_min.i: src/nonlinear/line_min.cpp.i

.PHONY : src/nonlinear/line_min.i

# target to preprocess a source file
src/nonlinear/line_min.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/line_min.cpp.i
.PHONY : src/nonlinear/line_min.cpp.i

src/nonlinear/line_min.s: src/nonlinear/line_min.cpp.s

.PHONY : src/nonlinear/line_min.s

# target to generate assembly for a file
src/nonlinear/line_min.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/line_min.cpp.s
.PHONY : src/nonlinear/line_min.cpp.s

src/nonlinear/lmlsqr.o: src/nonlinear/lmlsqr.cpp.o

.PHONY : src/nonlinear/lmlsqr.o

# target to build an object file
src/nonlinear/lmlsqr.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/lmlsqr.cpp.o
.PHONY : src/nonlinear/lmlsqr.cpp.o

src/nonlinear/lmlsqr.i: src/nonlinear/lmlsqr.cpp.i

.PHONY : src/nonlinear/lmlsqr.i

# target to preprocess a source file
src/nonlinear/lmlsqr.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/lmlsqr.cpp.i
.PHONY : src/nonlinear/lmlsqr.cpp.i

src/nonlinear/lmlsqr.s: src/nonlinear/lmlsqr.cpp.s

.PHONY : src/nonlinear/lmlsqr.s

# target to generate assembly for a file
src/nonlinear/lmlsqr.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/lmlsqr.cpp.s
.PHONY : src/nonlinear/lmlsqr.cpp.s

src/nonlinear/minimize_unc.o: src/nonlinear/minimize_unc.cpp.o

.PHONY : src/nonlinear/minimize_unc.o

# target to build an object file
src/nonlinear/minimize_unc.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/minimize_unc.cpp.o
.PHONY : src/nonlinear/minimize_unc.cpp.o

src/nonlinear/minimize_unc.i: src/nonlinear/minimize_unc.cpp.i

.PHONY : src/nonlinear/minimize_unc.i

# target to preprocess a source file
src/nonlinear/minimize_unc.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/minimize_unc.cpp.i
.PHONY : src/nonlinear/minimize_unc.cpp.i

src/nonlinear/minimize_unc.s: src/nonlinear/minimize_unc.cpp.s

.PHONY : src/nonlinear/minimize_unc.s

# target to generate assembly for a file
src/nonlinear/minimize_unc.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/minimize_unc.cpp.s
.PHONY : src/nonlinear/minimize_unc.cpp.s

src/nonlinear/momentum.o: src/nonlinear/momentum.cpp.o

.PHONY : src/nonlinear/momentum.o

# target to build an object file
src/nonlinear/momentum.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/momentum.cpp.o
.PHONY : src/nonlinear/momentum.cpp.o

src/nonlinear/momentum.i: src/nonlinear/momentum.cpp.i

.PHONY : src/nonlinear/momentum.i

# target to preprocess a source file
src/nonlinear/momentum.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/momentum.cpp.i
.PHONY : src/nonlinear/momentum.cpp.i

src/nonlinear/momentum.s: src/nonlinear/momentum.cpp.s

.PHONY : src/nonlinear/momentum.s

# target to generate assembly for a file
src/nonlinear/momentum.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/momentum.cpp.s
.PHONY : src/nonlinear/momentum.cpp.s

src/nonlinear/newton.o: src/nonlinear/newton.cpp.o

.PHONY : src/nonlinear/newton.o

# target to build an object file
src/nonlinear/newton.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/newton.cpp.o
.PHONY : src/nonlinear/newton.cpp.o

src/nonlinear/newton.i: src/nonlinear/newton.cpp.i

.PHONY : src/nonlinear/newton.i

# target to preprocess a source file
src/nonlinear/newton.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/newton.cpp.i
.PHONY : src/nonlinear/newton.cpp.i

src/nonlinear/newton.s: src/nonlinear/newton.cpp.s

.PHONY : src/nonlinear/newton.s

# target to generate assembly for a file
src/nonlinear/newton.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/newton.cpp.s
.PHONY : src/nonlinear/newton.cpp.s

src/nonlinear/nlcgd.o: src/nonlinear/nlcgd.cpp.o

.PHONY : src/nonlinear/nlcgd.o

# target to build an object file
src/nonlinear/nlcgd.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/nlcgd.cpp.o
.PHONY : src/nonlinear/nlcgd.cpp.o

src/nonlinear/nlcgd.i: src/nonlinear/nlcgd.cpp.i

.PHONY : src/nonlinear/nlcgd.i

# target to preprocess a source file
src/nonlinear/nlcgd.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/nlcgd.cpp.i
.PHONY : src/nonlinear/nlcgd.cpp.i

src/nonlinear/nlcgd.s: src/nonlinear/nlcgd.cpp.s

.PHONY : src/nonlinear/nlcgd.s

# target to generate assembly for a file
src/nonlinear/nlcgd.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/nlcgd.cpp.s
.PHONY : src/nonlinear/nlcgd.cpp.s

src/nonlinear/sgd.o: src/nonlinear/sgd.cpp.o

.PHONY : src/nonlinear/sgd.o

# target to build an object file
src/nonlinear/sgd.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/sgd.cpp.o
.PHONY : src/nonlinear/sgd.cpp.o

src/nonlinear/sgd.i: src/nonlinear/sgd.cpp.i

.PHONY : src/nonlinear/sgd.i

# target to preprocess a source file
src/nonlinear/sgd.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/sgd.cpp.i
.PHONY : src/nonlinear/sgd.cpp.i

src/nonlinear/sgd.s: src/nonlinear/sgd.cpp.s

.PHONY : src/nonlinear/sgd.s

# target to generate assembly for a file
src/nonlinear/sgd.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/sgd.cpp.s
.PHONY : src/nonlinear/sgd.cpp.s

src/nonlinear/simplex.o: src/nonlinear/simplex.cpp.o

.PHONY : src/nonlinear/simplex.o

# target to build an object file
src/nonlinear/simplex.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/simplex.cpp.o
.PHONY : src/nonlinear/simplex.cpp.o

src/nonlinear/simplex.i: src/nonlinear/simplex.cpp.i

.PHONY : src/nonlinear/simplex.i

# target to preprocess a source file
src/nonlinear/simplex.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/simplex.cpp.i
.PHONY : src/nonlinear/simplex.cpp.i

src/nonlinear/simplex.s: src/nonlinear/simplex.cpp.s

.PHONY : src/nonlinear/simplex.s

# target to generate assembly for a file
src/nonlinear/simplex.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/simplex.cpp.s
.PHONY : src/nonlinear/simplex.cpp.s

src/nonlinear/wolfe_step.o: src/nonlinear/wolfe_step.cpp.o

.PHONY : src/nonlinear/wolfe_step.o

# target to build an object file
src/nonlinear/wolfe_step.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/wolfe_step.cpp.o
.PHONY : src/nonlinear/wolfe_step.cpp.o

src/nonlinear/wolfe_step.i: src/nonlinear/wolfe_step.cpp.i

.PHONY : src/nonlinear/wolfe_step.i

# target to preprocess a source file
src/nonlinear/wolfe_step.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/wolfe_step.cpp.i
.PHONY : src/nonlinear/wolfe_step.cpp.i

src/nonlinear/wolfe_step.s: src/nonlinear/wolfe_step.cpp.s

.PHONY : src/nonlinear/wolfe_step.s

# target to generate assembly for a file
src/nonlinear/wolfe_step.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/nonlinear/wolfe_step.cpp.s
.PHONY : src/nonlinear/wolfe_step.cpp.s

src/statistics/chi_sq.o: src/statistics/chi_sq.cpp.o

.PHONY : src/statistics/chi_sq.o

# target to build an object file
src/statistics/chi_sq.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/statistics/chi_sq.cpp.o
.PHONY : src/statistics/chi_sq.cpp.o

src/statistics/chi_sq.i: src/statistics/chi_sq.cpp.i

.PHONY : src/statistics/chi_sq.i

# target to preprocess a source file
src/statistics/chi_sq.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/statistics/chi_sq.cpp.i
.PHONY : src/statistics/chi_sq.cpp.i

src/statistics/chi_sq.s: src/statistics/chi_sq.cpp.s

.PHONY : src/statistics/chi_sq.s

# target to generate assembly for a file
src/statistics/chi_sq.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/statistics/chi_sq.cpp.s
.PHONY : src/statistics/chi_sq.cpp.s

src/statistics/distributions.o: src/statistics/distributions.cpp.o

.PHONY : src/statistics/distributions.o

# target to build an object file
src/statistics/distributions.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/statistics/distributions.cpp.o
.PHONY : src/statistics/distributions.cpp.o

src/statistics/distributions.i: src/statistics/distributions.cpp.i

.PHONY : src/statistics/distributions.i

# target to preprocess a source file
src/statistics/distributions.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/statistics/distributions.cpp.i
.PHONY : src/statistics/distributions.cpp.i

src/statistics/distributions.s: src/statistics/distributions.cpp.s

.PHONY : src/statistics/distributions.s

# target to generate assembly for a file
src/statistics/distributions.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/statistics/distributions.cpp.s
.PHONY : src/statistics/distributions.cpp.s

src/statistics/functions.o: src/statistics/functions.cpp.o

.PHONY : src/statistics/functions.o

# target to build an object file
src/statistics/functions.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/statistics/functions.cpp.o
.PHONY : src/statistics/functions.cpp.o

src/statistics/functions.i: src/statistics/functions.cpp.i

.PHONY : src/statistics/functions.i

# target to preprocess a source file
src/statistics/functions.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/statistics/functions.cpp.i
.PHONY : src/statistics/functions.cpp.i

src/statistics/functions.s: src/statistics/functions.cpp.s

.PHONY : src/statistics/functions.s

# target to generate assembly for a file
src/statistics/functions.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/statistics/functions.cpp.s
.PHONY : src/statistics/functions.cpp.s

src/statistics/tests.o: src/statistics/tests.cpp.o

.PHONY : src/statistics/tests.o

# target to build an object file
src/statistics/tests.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/statistics/tests.cpp.o
.PHONY : src/statistics/tests.cpp.o

src/statistics/tests.i: src/statistics/tests.cpp.i

.PHONY : src/statistics/tests.i

# target to preprocess a source file
src/statistics/tests.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/statistics/tests.cpp.i
.PHONY : src/statistics/tests.cpp.i

src/statistics/tests.s: src/statistics/tests.cpp.s

.PHONY : src/statistics/tests.s

# target to generate assembly for a file
src/statistics/tests.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/statistics/tests.cpp.s
.PHONY : src/statistics/tests.cpp.s

src/utility/cyc_queue.o: src/utility/cyc_queue.cpp.o

.PHONY : src/utility/cyc_queue.o

# target to build an object file
src/utility/cyc_queue.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/utility/cyc_queue.cpp.o
.PHONY : src/utility/cyc_queue.cpp.o

src/utility/cyc_queue.i: src/utility/cyc_queue.cpp.i

.PHONY : src/utility/cyc_queue.i

# target to preprocess a source file
src/utility/cyc_queue.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/utility/cyc_queue.cpp.i
.PHONY : src/utility/cyc_queue.cpp.i

src/utility/cyc_queue.s: src/utility/cyc_queue.cpp.s

.PHONY : src/utility/cyc_queue.s

# target to generate assembly for a file
src/utility/cyc_queue.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/utility/cyc_queue.cpp.s
.PHONY : src/utility/cyc_queue.cpp.s

src/utility/eval.o: src/utility/eval.cpp.o

.PHONY : src/utility/eval.o

# target to build an object file
src/utility/eval.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/utility/eval.cpp.o
.PHONY : src/utility/eval.cpp.o

src/utility/eval.i: src/utility/eval.cpp.i

.PHONY : src/utility/eval.i

# target to preprocess a source file
src/utility/eval.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/utility/eval.cpp.i
.PHONY : src/utility/eval.cpp.i

src/utility/eval.s: src/utility/eval.cpp.s

.PHONY : src/utility/eval.s

# target to generate assembly for a file
src/utility/eval.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/utility/eval.cpp.s
.PHONY : src/utility/eval.cpp.s

src/utility/meshgrid.o: src/utility/meshgrid.cpp.o

.PHONY : src/utility/meshgrid.o

# target to build an object file
src/utility/meshgrid.cpp.o:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/utility/meshgrid.cpp.o
.PHONY : src/utility/meshgrid.cpp.o

src/utility/meshgrid.i: src/utility/meshgrid.cpp.i

.PHONY : src/utility/meshgrid.i

# target to preprocess a source file
src/utility/meshgrid.cpp.i:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/utility/meshgrid.cpp.i
.PHONY : src/utility/meshgrid.cpp.i

src/utility/meshgrid.s: src/utility/meshgrid.cpp.s

.PHONY : src/utility/meshgrid.s

# target to generate assembly for a file
src/utility/meshgrid.cpp.s:
	$(MAKE) -f CMakeFiles/numerics.dir/build.make CMakeFiles/numerics.dir/src/utility/meshgrid.cpp.s
.PHONY : src/utility/meshgrid.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... numerics"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... install"
	@echo "... src/ODEs/IVP_solve.o"
	@echo "... src/ODEs/IVP_solve.i"
	@echo "... src/ODEs/IVP_solve.s"
	@echo "... src/ODEs/am1.o"
	@echo "... src/ODEs/am1.i"
	@echo "... src/ODEs/am1.s"
	@echo "... src/ODEs/am2.o"
	@echo "... src/ODEs/am2.i"
	@echo "... src/ODEs/am2.s"
	@echo "... src/ODEs/bdf23.o"
	@echo "... src/ODEs/bdf23.i"
	@echo "... src/ODEs/bdf23.s"
	@echo "... src/ODEs/cheb.o"
	@echo "... src/ODEs/cheb.i"
	@echo "... src/ODEs/cheb.s"
	@echo "... src/ODEs/diffmat.o"
	@echo "... src/ODEs/diffmat.i"
	@echo "... src/ODEs/diffmat.s"
	@echo "... src/ODEs/ivp_events.o"
	@echo "... src/ODEs/ivp_events.i"
	@echo "... src/ODEs/ivp_events.s"
	@echo "... src/ODEs/linear_bvp.o"
	@echo "... src/ODEs/linear_bvp.i"
	@echo "... src/ODEs/linear_bvp.s"
	@echo "... src/ODEs/nonlin_bvp.o"
	@echo "... src/ODEs/nonlin_bvp.i"
	@echo "... src/ODEs/nonlin_bvp.s"
	@echo "... src/ODEs/poisson.o"
	@echo "... src/ODEs/poisson.i"
	@echo "... src/ODEs/poisson.s"
	@echo "... src/ODEs/rk4.o"
	@echo "... src/ODEs/rk4.i"
	@echo "... src/ODEs/rk4.s"
	@echo "... src/ODEs/rk45.o"
	@echo "... src/ODEs/rk45.i"
	@echo "... src/ODEs/rk45.s"
	@echo "... src/ODEs/rk5i.o"
	@echo "... src/ODEs/rk5i.i"
	@echo "... src/ODEs/rk5i.s"
	@echo "... src/finite_dif.o"
	@echo "... src/finite_dif.i"
	@echo "... src/finite_dif.s"
	@echo "... src/integration/integrate.o"
	@echo "... src/integration/integrate.i"
	@echo "... src/integration/integrate.s"
	@echo "... src/integration/mcIntegrate.o"
	@echo "... src/integration/mcIntegrate.i"
	@echo "... src/integration/mcIntegrate.s"
	@echo "... src/interpolation/cinterp.o"
	@echo "... src/interpolation/cinterp.i"
	@echo "... src/interpolation/cinterp.s"
	@echo "... src/interpolation/interp.o"
	@echo "... src/interpolation/interp.i"
	@echo "... src/interpolation/interp.s"
	@echo "... src/interpolation/polyInterp.o"
	@echo "... src/interpolation/polyInterp.i"
	@echo "... src/interpolation/polyInterp.s"
	@echo "... src/interpolation/sincInterp.o"
	@echo "... src/interpolation/sincInterp.i"
	@echo "... src/interpolation/sincInterp.s"
	@echo "... src/kmeans.o"
	@echo "... src/kmeans.i"
	@echo "... src/kmeans.s"
	@echo "... src/nonlinear/adj_gd.o"
	@echo "... src/nonlinear/adj_gd.i"
	@echo "... src/nonlinear/adj_gd.s"
	@echo "... src/nonlinear/bfgs.o"
	@echo "... src/nonlinear/bfgs.i"
	@echo "... src/nonlinear/bfgs.s"
	@echo "... src/nonlinear/broyd.o"
	@echo "... src/nonlinear/broyd.i"
	@echo "... src/nonlinear/broyd.s"
	@echo "... src/nonlinear/cgd.o"
	@echo "... src/nonlinear/cgd.i"
	@echo "... src/nonlinear/cgd.s"
	@echo "... src/nonlinear/fpi.o"
	@echo "... src/nonlinear/fpi.i"
	@echo "... src/nonlinear/fpi.s"
	@echo "... src/nonlinear/fzero.o"
	@echo "... src/nonlinear/fzero.i"
	@echo "... src/nonlinear/fzero.s"
	@echo "... src/nonlinear/genetic.o"
	@echo "... src/nonlinear/genetic.i"
	@echo "... src/nonlinear/genetic.s"
	@echo "... src/nonlinear/line_min.o"
	@echo "... src/nonlinear/line_min.i"
	@echo "... src/nonlinear/line_min.s"
	@echo "... src/nonlinear/lmlsqr.o"
	@echo "... src/nonlinear/lmlsqr.i"
	@echo "... src/nonlinear/lmlsqr.s"
	@echo "... src/nonlinear/minimize_unc.o"
	@echo "... src/nonlinear/minimize_unc.i"
	@echo "... src/nonlinear/minimize_unc.s"
	@echo "... src/nonlinear/momentum.o"
	@echo "... src/nonlinear/momentum.i"
	@echo "... src/nonlinear/momentum.s"
	@echo "... src/nonlinear/newton.o"
	@echo "... src/nonlinear/newton.i"
	@echo "... src/nonlinear/newton.s"
	@echo "... src/nonlinear/nlcgd.o"
	@echo "... src/nonlinear/nlcgd.i"
	@echo "... src/nonlinear/nlcgd.s"
	@echo "... src/nonlinear/sgd.o"
	@echo "... src/nonlinear/sgd.i"
	@echo "... src/nonlinear/sgd.s"
	@echo "... src/nonlinear/simplex.o"
	@echo "... src/nonlinear/simplex.i"
	@echo "... src/nonlinear/simplex.s"
	@echo "... src/nonlinear/wolfe_step.o"
	@echo "... src/nonlinear/wolfe_step.i"
	@echo "... src/nonlinear/wolfe_step.s"
	@echo "... src/statistics/chi_sq.o"
	@echo "... src/statistics/chi_sq.i"
	@echo "... src/statistics/chi_sq.s"
	@echo "... src/statistics/distributions.o"
	@echo "... src/statistics/distributions.i"
	@echo "... src/statistics/distributions.s"
	@echo "... src/statistics/functions.o"
	@echo "... src/statistics/functions.i"
	@echo "... src/statistics/functions.s"
	@echo "... src/statistics/tests.o"
	@echo "... src/statistics/tests.i"
	@echo "... src/statistics/tests.s"
	@echo "... src/utility/cyc_queue.o"
	@echo "... src/utility/cyc_queue.i"
	@echo "... src/utility/cyc_queue.s"
	@echo "... src/utility/eval.o"
	@echo "... src/utility/eval.i"
	@echo "... src/utility/eval.s"
	@echo "... src/utility/meshgrid.o"
	@echo "... src/utility/meshgrid.i"
	@echo "... src/utility/meshgrid.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

